include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: warning
    unused_import: warning
    dead_code: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_const
